# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
jinja:
  version: 2.11.3 # 指定使用Jinja2 2.11.3版本
mkdocs:
  configuration: mkdocs.yml