name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
        version: '6.40.0'
        sourcePath: 'src/main/java'
        rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'

    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1

    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1

    - name: Build and Test
      uses: docker://maven:3.6.3-jdk-11-slim
      with:
        args: mvn -B -e clean test jacoco:report
      env:
        XMLSTARLET_INSTALL: /usr/bin/xmlstarlet

    - name: Check code coverage
      run: |
        sudo apt-get update && sudo apt-get install -y xmlstarlet
        total_coverage=$(xmlstarlet sel -t -v "sum(//counter[@type='LINE']/@covered)" -n target/site/jacoco/jacoco.xml)
        total_lines=$(xmlstarlet sel -t -v "sum(//counter[@type='LINE']/@missed)" -n target/site/jacoco/jacoco.xml)
        echo "Code coverage: $(echo "scale=2; $total_coverage * 100 / ($total_coverage + $total_lines)" | bc)%"
        if [ $(($total_coverage * 100 / ($total_coverage + $total_lines))) -lt 80 ]; then
          echo "Code coverage is below 80%."
          exit 1
        fi
      env:
        XMLSTARLET_INSTALL: /usr/bin/xmlstarlet